ClassDiagram
    { class Login{ 
    -ID: int
    -NomeUsuario:string
    -Senha:string
    +autenticar(NomeUsuario string, Senha string):boolean
    +logout():void
    +exibir():string

    
    
    
    }